workflows:
  mood-app-release:
    name: Mood App Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - google_play
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@gmail.com
